### PR TITLE
Fix staging deploys

### PR DESCRIPTION
**Pull request by nickgartmann**
For some reason, `System.fetch_env!/1` is working, when `System.get_env/1` was not. Fix per recommendation from Mitch.

### CODE REVIEW

**Comment by abstractcoder** [comment]
I ran into the same issue with the prod.secret.exs, but  I forgot to fix it in staging.

https://github.com/DigitalPublicWorks/digital-public-works/blob/master/config/prod.secret.exs

I think its a syntax issue, and I was able to fix it by making the multiline string the last argument

**Comment by abstractcoder** [comment]
You might also be able to fix it with adding parentheses to the raise call, but I didn't try that.

**Comment by nickgartmann** [comment]
Swapping to that and testing it

**Comment by nickgartmann** [comment]
Looks like it worked 👍

**Pull request merged**
